### ISSUE TITLE
Create docker image for oml-bikeshed 

### ISSUE THREAD

**Issue by dwagmuse** [opencaesar/oml-tools#6]
## User Story
To make it easier to run oml-bikeshed in a travis or Jenkins CI process I want to containerize the app to run under docker.

## Acceptance Criteria
- [ ] able to run converter as a docker image

## Sub-task List
- [ ] Deliver Dockerfile that defines the docker image
- [ ] Build and deploy docker image somewhere it can be accessed for CI builds
- [ ] Explain how to use the docker image in README

**Comment by melaasar** [comment]
There is a Gradle [task](https://github.com/opencaesar/oml-tools/blob/master/oml-tools/oml-bikeshed-gradle/README.md) that can run oml2bikeshed from a Gradle script. Would this suffice?

**Comment by dwagmuse** [comment]
That helps. The intent was to be able to run bikeshed itself in a container so user doesn't have to install it or to run in CI.
Looks like there is a container that can do this:

https://hub.docker.com/r/bikebike/bikeshed

Ok to close

**Comment by melaasar** [comment]
Thanks for confirming no further action is needed. Closing.
